INSERT INTO `cook_book` VALUES (1, '油麦菜', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (2, '酱爆猪肝', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (3, '蒜泥生菜', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (4, '酸豇豆肉丝', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (5, '蚝油生菜', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (6, '香菇青菜', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (7, '松仁玉米', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (8, '青椒土豆丝', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (9, '玉米烙', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (10, '酸辣土豆丝', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (11, '青椒肉片', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (12, '麻辣豆腐', 16, 1, NULL);
INSERT INTO `cook_book` VALUES (13, '黄瓜肉片', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (14, '清炒波菜', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (15, '木耳炒蛋', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (16, '雪菜粉皮', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (17, '苦瓜肉片', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (18, '青椒香干丝', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (19, '渔香肉丝', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (20, '酸辣白菜', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (21, '椒盐排条', 32, 1, NULL);
INSERT INTO `cook_book` VALUES (22, '芹菜香干丝', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (23, '糖醋排条', 32, 1, NULL);
INSERT INTO `cook_book` VALUES (24, '虾仁跑蛋', 20, 1, NULL);
INSERT INTO `cook_book` VALUES (25, '小葱跑蛋', 20, 1, NULL);
INSERT INTO `cook_book` VALUES (26, '蒜苔肉丝', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (27, '蒜泥刀豆', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (28, '剁椒肚丝', 42, 1, NULL);
INSERT INTO `cook_book` VALUES (29, '干煸刀豆', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (30, '川味回锅肉', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (31, '刀豆土豆', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (32, '大蒜咸肉', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (33, '蒜泥米茜', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (34, '山药木耳肉片', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (35, '蒜泥空心菜', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (36, '莴笋木耳肉片', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (37, '番茄炒蛋', 20, 1, NULL);
INSERT INTO `cook_book` VALUES (38, '韭黄炒蛋', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (39, '宫保鸡丁', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (40, '韭菜炒蛋', 20, 1, NULL);
INSERT INTO `cook_book` VALUES (41, '湘辣鸡丁', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (42, '手撕包菜', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (43, '家常豆腐', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (44, '酒香草头', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (45, '腊肠荷兰豆', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (46, '酱爆茄子', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (47, '腐竹肉片', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (48, '渔香茄子', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (49, '滑炒牛蛙', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (50, '西芹百合', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (51, '京葱爆牛肉', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (52, '上汤娃娃菜', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (53, '蚝油牛肉', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (54, '荠菜山药', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (55, '扬州干丝', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (56, '尖椒牛肉', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (57, '烂糊肉丝', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (58, '芹菜干丝肉丝', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (59, '什锦西兰花', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (60, '青椒干丝肉丝', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (61, '地三鲜', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (62, '青豆虾仁', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (63, '小炒肉', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (64, '芹菜野山椒牛肉丝', 45, 1, NULL);
INSERT INTO `cook_book` VALUES (65, '秘制红烧肉', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (66, '盐花生', 12, 1, NULL);
INSERT INTO `cook_book` VALUES (67, '雪菜黄鱼', 39, 1, NULL);
INSERT INTO `cook_book` VALUES (68, '雪菜大肠', 39, 1, NULL);
INSERT INTO `cook_book` VALUES (69, '皮蛋豆腐', 12, 1, NULL);
INSERT INTO `cook_book` VALUES (70, '洋葱大肠', 39, 1, NULL);
INSERT INTO `cook_book` VALUES (71, '香油皮蛋', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (72, '尖椒卤牛肉', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (73, '凉拌黄瓜', 12, 1, NULL);
INSERT INTO `cook_book` VALUES (74, '洋葱土豆牛肉', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (75, '红烧扁鱼', 35, 1, NULL);
INSERT INTO `cook_book` VALUES (76, '炝花生', 12, 1, NULL);
INSERT INTO `cook_book` VALUES (77, '葱烧鲫鱼', 30, 1, NULL);
INSERT INTO `cook_book` VALUES (78, '红烧鸡块', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (79, '咖哩鸡块', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (80, '红烧带鱼', 45, 1, NULL);
INSERT INTO `cook_book` VALUES (81, '干煎带鱼', 45, 1, NULL);
INSERT INTO `cook_book` VALUES (82, '红烧小黄鱼', 42, 1, NULL);
INSERT INTO `cook_book` VALUES (83, '蕃茄蛋汤', 15, 1, NULL);
INSERT INTO `cook_book` VALUES (84, '干煎小黄鱼', 45, 1, NULL);
INSERT INTO `cook_book` VALUES (85, '紫菜蛋汤', 15, 1, NULL);
INSERT INTO `cook_book` VALUES (86, '清蒸鲈鱼', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (87, '榨菜肉丝汤', 15, 1, NULL);
INSERT INTO `cook_book` VALUES (88, '酸菜鱼片', 38, 1, NULL);
INSERT INTO `cook_book` VALUES (89, '水煮鱼片', 38, 1, NULL);
INSERT INTO `cook_book` VALUES (90, '酸辣汤', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (91, '毛血旺', 45, 1, NULL);
INSERT INTO `cook_book` VALUES (92, '咸肉冬瓜汤', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (93, '水煮牛肉', 58, 1, NULL);
INSERT INTO `cook_book` VALUES (94, '小排冬瓜汤', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (95, '油爆虾', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (96, '剁椒鱼头', 88, 1, NULL);
INSERT INTO `cook_book` VALUES (97, '青菜猪肝汤', 20, 1, NULL);
INSERT INTO `cook_book` VALUES (98, '肉米蒸蛋', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (99, '鲫鱼豆腐汤', 28, 1, NULL);
INSERT INTO `cook_book` VALUES (100, '青鱼头豆腐汤', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (101, '荠菜豆腐羹', 18, 1, NULL);
INSERT INTO `cook_book` VALUES (102, '干锅大虾', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (103, '香菇面筋煲', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (104, '肉米粉丝煲', 22, 1, NULL);
INSERT INTO `cook_book` VALUES (105, '干锅大肠', 48, 1, NULL);
INSERT INTO `cook_book` VALUES (106, '干锅鸡', 45, 1, NULL);
INSERT INTO `cook_book` VALUES (107, '干锅牛蛙', 55, 1, NULL);
INSERT INTO `cook_book` VALUES (108, '牛肉锅仔', 88, 1, NULL);
INSERT INTO `cook_book` VALUES (109, '羊肉锅仔', 88, 1, NULL);
INSERT INTO `cook_book` VALUES (110, '米饭', 2, 1, NULL);
INSERT INTO `cook_book` VALUES (111, '胖头鱼豆腐煲', 88, 1, NULL);
INSERT INTO `cook_book` VALUES (112, '干锅包菜', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (113, '干锅有机花菜', 25, 1, NULL);
INSERT INTO `cook_book` VALUES (114, '招牌腊味煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (115, '香菇滑鸡煲仔饭', 7, 2, 13);
INSERT INTO `cook_book` VALUES (116, '川味腊肠煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (117, '豉汁排骨煲仔饭', 29, 2, 14);
INSERT INTO `cook_book` VALUES (118, '腊鸡腿煲仔饭', 26, 2, 13);
INSERT INTO `cook_book` VALUES (119, '咸蛋黄腊味煲仔饭', 29, 2, 13);
INSERT INTO `cook_book` VALUES (120, '瘦身藜麦米招牌腊味煲仔饭', 33, 2, 13);
INSERT INTO `cook_book` VALUES (121, '瘦身藜麦米香菇滑鸡煲仔饭', 33, 2, 13);
INSERT INTO `cook_book` VALUES (122, '瘦身藜麦米麻辣鸡丁煲仔饭', 33, 2, 13);
INSERT INTO `cook_book` VALUES (123, '红薯招牌腊味煲仔饭', 31, 2, 13);
INSERT INTO `cook_book` VALUES (124, '红薯香菇滑鸡煲仔饭', 31, 2, 13);
INSERT INTO `cook_book` VALUES (125, '红薯麻辣鸡丁煲仔饭', 31, 2, 13);
INSERT INTO `cook_book` VALUES (126, '蜜汁叉烧煲仔饭', 31, 2, 15);
INSERT INTO `cook_book` VALUES (127, '回锅肉煲仔饭', 25, 2, 12);
INSERT INTO `cook_book` VALUES (128, '麻辣鸡丁煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (129, '黑椒牛肉煲仔饭', 31, 2, 15);
INSERT INTO `cook_book` VALUES (130, '翡翠掌中宝煲仔饭', 29, 2, 15);
INSERT INTO `cook_book` VALUES (131, '铁板鱿鱼煲仔饭', 28, 2, 13);
INSERT INTO `cook_book` VALUES (132, '翡翠什锦水晶虾仁煲仔饭', 36, 2, 21);
INSERT INTO `cook_book` VALUES (133, '农家泡椒鸭胗煲仔饭', 28, 2, 13);
INSERT INTO `cook_book` VALUES (134, '麻辣鹅肠煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (135, '脆笋牛肚煲仔饭', 29, 2, 13);
INSERT INTO `cook_book` VALUES (136, '剁椒牛蛙煲仔饭', 29, 2, 15);
INSERT INTO `cook_book` VALUES (137, '外婆菜肉饼煲仔饭', 28, 2, 13);
INSERT INTO `cook_book` VALUES (138, '雪菜脆笋肉丝煲仔饭', 24, 2, 11);
INSERT INTO `cook_book` VALUES (139, '特色鸭肝腊味煲仔饭', 29, 2, 12);
INSERT INTO `cook_book` VALUES (140, '原汁牛肉煲仔饭', 31, 2, 14);
INSERT INTO `cook_book` VALUES (141, '咖喱牛腩煲仔饭', 33, 2, 16);
INSERT INTO `cook_book` VALUES (142, '红烧肉煲仔饭', 28, 2, 16);
INSERT INTO `cook_book` VALUES (143, '肥肠煲仔饭', 31, 2, 16);
INSERT INTO `cook_book` VALUES (144, '腊味藕丁肉饼煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (145, '咖喱鸡块煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (146, '酱肉煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (147, '酱鸭煲仔饭 ', 25, 2, 12);
INSERT INTO `cook_book` VALUES (148, '全素煲仔饭 ', 21, 2, 12);
INSERT INTO `cook_book` VALUES (149, '剁椒鲴鱼翅煲仔饭 ', 28, 2, 13);
INSERT INTO `cook_book` VALUES (150, '梅干菜肉煲仔饭', 27, 2, 13);
INSERT INTO `cook_book` VALUES (151, '秘制酱香肉煲仔饭', 29, 2, 14);
INSERT INTO `cook_book` VALUES (152, '排骨土豆粉砂锅', 29, 2, 14);
INSERT INTO `cook_book` VALUES (153, '牛肚土豆粉砂锅', 28, 2, 13);
INSERT INTO `cook_book` VALUES (154, '鹅肠土豆粉砂锅', 27, 2, 13);
INSERT INTO `cook_book` VALUES (155, '川味味腊肠土豆粉砂锅', 27, 2, 13);
INSERT INTO `cook_book` VALUES (156, '藕丁肉丸土豆粉砂锅', 26, 2, 13);
INSERT INTO `cook_book` VALUES (157, '酱香肉土豆粉砂锅', 29, 2, 14);
INSERT INTO `cook_book` VALUES (158, '牛蛙士豆粉砂锅', 29, 2, 15);
INSERT INTO `cook_book` VALUES (159, '咸肉土豆粉砂锅', 28, 2, 13);
INSERT INTO `cook_book` VALUES (160, '香菇鸡块土豆粉砂锅', 28, 2, 12);
INSERT INTO `cook_book` VALUES (161, '原汁牛肉土豆粉砂锅', 29, 2, 13);
INSERT INTO `cook_book` VALUES (162, '加瘦身藜麦米', 6, 2, NULL);
INSERT INTO `cook_book` VALUES (163, '加红薯', 4, 2, NULL);
INSERT INTO `cook_book` VALUES (164, '加五谷杂粮', 3, 2, NULL);
INSERT INTO `cook_book` VALUES (165, '加窝蛋', 3, 2, NULL);
INSERT INTO `cook_book` VALUES (166, '加蔬菜', 3, 2, NULL);
INSERT INTO `cook_book` VALUES (167, '避风塘水晶虾饺皇', 40, 2, NULL);
INSERT INTO `cook_book` VALUES (168, '避风塘蜜汁叉烧包', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (169, '避风塘奶黄包', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (170, '秘制鲜肉小笼包', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (171, '秘制烧肉蘑菇包', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (172, '香甜软糯紫薯包', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (173, '香甜酒酿小丸子', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (174, '竹荪炖老鸭汤', 20, 2, NULL);
INSERT INTO `cook_book` VALUES (175, '无花果炖乌鸡汤', 18, 2, NULL);
INSERT INTO `cook_book` VALUES (176, '灵芝炖乳鸽汤', 23, 2, NULL);
INSERT INTO `cook_book` VALUES (177, '生鱼片粥+重油秘制咸鸭蛋+开胃小菜', 21, 2, NULL);
INSERT INTO `cook_book` VALUES (178, '瑶柱虾仁粥+重油秘制咸鸭蛋+开胃小菜', 22, 2, NULL);
INSERT INTO `cook_book` VALUES (179, '牛肉窝蛋粥+重油秘制咸鸭蛋+开胃小菜', 22, 2, NULL);
INSERT INTO `cook_book` VALUES (180, '皮蛋瘦肉粥+重油秘制咸鸭蛋+开胃小菜', 19, 2, NULL);
INSERT INTO `cook_book` VALUES (181, '素土豆粉砂锅', 22, 2, NULL);
INSERT INTO `cook_book` VALUES (182, '重庆酸辣粉', 21, 2, NULL);
INSERT INTO `cook_book` VALUES (183, '三黄鸡(堂吃)', 38, 3, NULL);
INSERT INTO `cook_book` VALUES (184, '自三黄鸡(外卖)', 36, 3, NULL);
INSERT INTO `cook_book` VALUES (185, '鸡胗、肝 ', 46, 3, NULL);
INSERT INTO `cook_book` VALUES (186, '鸡爪', 32, 3, NULL);
INSERT INTO `cook_book` VALUES (187, '香糟毛豆 ', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (188, '凉拌黄瓜 ', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (189, '黑木耳 ', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (190, '鸡丝凉皮 ', 16, 3, NULL);
INSERT INTO `cook_book` VALUES (191, '红枣南瓜 ', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (192, '鲜肉锅贴 ', 8, 3, NULL);
INSERT INTO `cook_book` VALUES (193, '虾仁锅贴 ', 16, 3, NULL);
INSERT INTO `cook_book` VALUES (194, '上海鲜肉小笼', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (195, '虾仁小笼 ', 18, 3, NULL);
INSERT INTO `cook_book` VALUES (196, '桂花糕 ', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (197, '米馒头 ', 6, 3, NULL);
INSERT INTO `cook_book` VALUES (198, '蘑菇包 ', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (199, '双色糕 ', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (200, '鸡骨面 ', 15, 3, NULL);
INSERT INTO `cook_book` VALUES (201, '辣肉面 ', 20, 3, NULL);
INSERT INTO `cook_book` VALUES (202, '红烧牛肉面', 23, 3, NULL);
INSERT INTO `cook_book` VALUES (203, '鸡汤面 ', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (204, '咸菜肉丝面', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (205, '台式牛肉面', 30, 3, NULL);
INSERT INTO `cook_book` VALUES (206, '肥肠小面 ', 25, 3, NULL);
INSERT INTO `cook_book` VALUES (207, '黄豆猪手面', 26, 3, NULL);
INSERT INTO `cook_book` VALUES (208, '老鸭汤面 ', 26, 3, NULL);
INSERT INTO `cook_book` VALUES (209, '葱油面 ', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (210, '炸酱面 ', 13, 3, NULL);
INSERT INTO `cook_book` VALUES (211, '热干面 ', 15, 3, NULL);
INSERT INTO `cook_book` VALUES (212, '油咖喱牛肉炒面', 26, 3, NULL);
INSERT INTO `cook_book` VALUES (213, '鱼香肉丝面(饭)', 22, 3, NULL);
INSERT INTO `cook_book` VALUES (214, '台式卤肉面(饭)', 22, 3, NULL);
INSERT INTO `cook_book` VALUES (215, '猪肝面(饭)', 17, 3, NULL);
INSERT INTO `cook_book` VALUES (216, '宫保鸡丁面(饭)', 7, 3, NULL);
INSERT INTO `cook_book` VALUES (217, '松茸菌菇(饭)', 22, 3, NULL);
INSERT INTO `cook_book` VALUES (218, '鸡杂面(饭)', 22, 3, NULL);
INSERT INTO `cook_book` VALUES (219, '酸辣粉 ', 8, 3, NULL);
INSERT INTO `cook_book` VALUES (220, '冷面', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (221, '另加头 ', 8, 3, NULL);
INSERT INTO `cook_book` VALUES (222, '鲜肉小馄饨', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (223, '虾仁小馄饨', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (224, '香菇大馄饨', 16, 3, NULL);
INSERT INTO `cook_book` VALUES (225, '虾仁大馄饨', 22, 3, NULL);
INSERT INTO `cook_book` VALUES (226, '皮蛋瘦肉粥', 11, 3, NULL);
INSERT INTO `cook_book` VALUES (227, '鸡粥', 5, 3, NULL);
INSERT INTO `cook_book` VALUES (228, '小米南瓜粥', 5, 3, NULL);
INSERT INTO `cook_book` VALUES (229, '全色血汤 ', 10, 3, NULL);
INSERT INTO `cook_book` VALUES (230, '牛肉粉丝汤', 12, 3, NULL);
INSERT INTO `cook_book` VALUES (231, '人参鸡汤', 19, 3, NULL);
INSERT INTO `cook_book` VALUES (232, '药膳排骨汤', 19, 3, NULL);
